# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Check Svelte
        run: npm run check:svelte
      - name: Check Prettier
        run: npm run check:prettier
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: public/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: public/build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
